### ISSUE TITLE
Error while running demo code. InvalidData: data did not match any variant of untagged enum ArgsEnum

### ISSUE THREAD

**Issue by borsemayur2** [open-source-labs/obsidian#51]
```
─ deno run --allow-env --allow-read server.ts                                                                                                                        ─╯ 
error: Uncaught (in promise) InvalidData: data did not match any variant of untagged enum ArgsEnum
    throw new ErrorClass(res.err.message);
          ^
    at processResponse (deno:core/core.js:213:11)
    at Object.jsonOpAsync (deno:core/core.js:231:12)
    at async Object.connect (deno:runtime/js/30_net.js:199:13)
    at async RedisConnection.connectThunkified (https://raw.githubusercontent.com/keroxp/deno-redis/master/connection.ts:74:11)
    at async RedisConnection.connect (https://raw.githubusercontent.com/keroxp/deno-redis/master/connection.ts:123:5)
    at async connect (https://raw.githubusercontent.com/keroxp/deno-redis/master/redis.ts:2240:3)    at async https://deno.land/x/obsidian@2.0.1/src/CacheClassServer.js:10:11
```

**Comment by borsemayur2** [comment]
Deno version: 1.7.5

**Comment by watcharaphat** [comment]
I'm getting the same issue.

deno 1.8.1 (release, x86_64-apple-darwin)
v8 9.0.257.3
typescript 4.2.2

**Comment by travismfrank** [comment]
Hi folks- could either of you include exactly what your server file looks like?  I'll be updating the documentation in the next couple of weeks (see: #53) for Obsidian 3.0, so I'd love to iron out this problem.  Thanks!

**Comment by borsemayur2** [comment]
Here's [server.ts](https://github.com/borsemayur2/obsidian-demo/blob/main/server.ts) file from [obisidian-demo](https://github.com/borsemayur2/obsidian-demo/blob/main/server.ts) repo
