### ISSUE TITLE
TypeError: Error parsing args: data did not match any variant of untagged enum ArgsEnum on import

### ISSUE THREAD

**Issue by tv42** [open-source-labs/obsidian#64]
```
$ deno repl --eval 'import { gql } from "https://deno.land/x/obsidian@v3.2.1.1/mod.ts"'
error in --eval flag. Uncaught TypeError: Error parsing args: data did not match any variant of untagged enum ArgsEnum
    at deno:core/01_core.js:101:46
    at unwrapOpResult (deno:core/01_core.js:121:13)
    at Object.opAsync (deno:core/01_core.js:130:28)
    at opConnect (deno:ext/net/01_net.js:42:17)
    at Object.connect (deno:ext/net/01_net.js:219:19)
    at RedisConnection.connectThunkified (https://deno.land/x/redis@v0.24.0/connection.ts:74:22)
    at RedisConnection.connect (https://deno.land/x/redis@v0.24.0/connection.ts:123:16)
    at connect (https://deno.land/x/redis@v0.24.0/redis.ts:2275:20)
    at https://deno.land/x/obsidian@v3.2.1.1/src/quickCache.js:12:17
Deno 1.14.3
exit using ctrl+d or close()
>
```

**Comment by meekle** [comment]
How much of the install instructions did you follow?  At first glance it appears like you either may not have redis open or you may not have set up your .ENV file?

**Comment by tv42** [comment]
I have none of that set up, I wanted to just do an interactive experiment to see how obsidian does some stuff related to graphql schemas. The exception thrown doesn't seem like a great way to handle missing configuration, especially when I imported a module that shouldn't use Redis...

**Comment by meekle** [comment]
"import gql from 'https://deno.land/x/oak_graphql@0.6.2/graphql-tag/index.ts';"
but we'll add more explicit errors to our todo
